### ISSUE TITLE
Crash on Android with API level lower 24

### ISSUE THREAD

**Issue by BohdanSamusko** [hoopit/chatsdk#23]
The **getOrDefault** method was added in API level 24 and runtimes below API level 24 don't have that method. That's why it's not working on Android API level 21.

What should be fix: replace method **getOrDefault** with some alternative one in class **io.hoopit.chatsdk.realtimeadapter.repository.Model** (**line 229**)

<img width="1459" alt="Screen Shot 2019-10-16 at 11 12 12" src="https://user-images.githubusercontent.com/10655043/67079917-bd9ebd80-f19c-11e9-9f72-a791147bf559.png">

**Comment by ezet** [comment]
This has been fixed in fdfaf177d7260f4ed1bb30914d1c27529c030a40
